[package]
authors = ["Kisio Digital <team.coretools@kisio.com>", "Guillaume Pinot <texitoi@texitoi.eu>"]
name = "transit_model"
version = "0.36.1"
license = "AGPL-3.0-only"
description = "Transit data management"
repository = "https://github.com/CanalTP/transit_model"
keywords = ["ntfs", "gtfs", "netex", "navitia", "transit"]
categories = ["data-structures", "encoding", "parser-implementations"]
edition = "2018"
readme = "README.md"
exclude = [
	".gitignore",
	".mergify.yml",
	"CONTRIBUTING.md",
	"README.md",
	"examples/",
	"src/documentation/",
	"tests/",
]

[workspace]
members = [
	"gtfs2netexfr",
	"gtfs2ntfs",
	"ntfs2gtfs",
	"ntfs2netexfr",
	"model-builder",
	"ntfs2ntfs",
	"restrict-validity-period",
]

[features]
xmllint = ["proj"]
# Experimental feature, use at your own risks
mutable-model = []

[dependencies]
chrono = "0.4"
chrono-tz = { version = "0.5", features = ["serde"] }
csv = "1"
derivative = "2"
failure = "0.1"
geo = "0.18"
iso4217 = "0.3"
lazy_static = "1"
log = "0.4"
md5 = "0.7"
# do not upgrade to 'minidom:0.13.0' (too strict on namespaces and no XML comment support)
# https://github.com/CanalTP/transit_model/pull/746
minidom = "0.12"
minidom_ext = "1"
minidom_writer = "1"
num-traits = "0.2"
pretty_assertions = "0.6"
proj = { version = "0.22", optional = true }
quick-xml = "0.18"
relational_types = "2"
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
skip_error = { version = "1.1", features = ["log"] }
tempfile = "3"
thiserror = "1"
typed_index_collection = "2"
walkdir = "2"
wkt = "0.9"
zip = { version = "0.5", default-features = false, features = ["deflate"] }
git-version = "0.3"

[[test]]
name = "write_netex_france"
path = "tests/write_netex_france.rs"
required-features = ["proj"]

[dev-dependencies]
approx = "0.3"
rust_decimal_macros = "1"
testing_logger = "0.1"
transit_model_builder = { path = "./model-builder"}
